# 通用配置
common:
  # [debug, info, warn, error]
  log-level: "info"
  log-file: "logs/srs-sip.log"

# GB28181配置
gb28181:
  serial: "34020000002000000001"
  realm: "3402000000"
  host: "0.0.0.0"
  port: 5060
  auth:
    enable: false
    password: "123456"

# HTTP服务配置
http:
  listen: 8025
  dir: ./html
